### ISSUE TITLE
我有4000多张照片和1000多个视频，再导入时如何保持照片时间不变呢？

### ISSUE THREAD

**Issue by 0xhhhhh** [Ryan-the-hito/Coconut#1]
用系统自带的App导入后时间序列全都错乱了

**Comment by Ryan-the-hito** [comment]
天哪……这么多照片和视频，最好还是使用别的储存介质。照片库、iCloud 可真没那么保险。去 V2EX 上搜搜就经常是大量托管图片库然后出问题的。我写这个软件是为了日常性的那种照片同步，比如我截个图，或者有人微信发我什么照片，我一存到对应的访达路径里，它就给我同步进照片库，过一会儿我就在 iPhone 上也能看到这张图，等下再用手机发图的时候就不用专门一张张 AirDrop 了。这种需求适合用这个软件。大量照片一次性导入，基本上没有不出现点小插曲的……真的建议永久性照片管理远离 iCloud 和相关软件设施。苹果生态的强项不在这里。

**Comment by 0xhhhhh** [comment]
目前的照片全部存在NAS里面，是打算想把NAS的照片导入到iCloud，这样方便查看，然后NAS只用来备份就好了。

**Comment by Ryan-the-hito** [comment]
还有别的备用就挺好的。但这个时间问题，基本上无解。应该是会都当成你导入的时间。
